<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>EditButton</name>
   <tag></tag>
   <elementGuidId>9a9cae2b-30fa-41f6-9fd6-cace36e87ca8</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>(//lightning-button[@class='btn-group'])[1]/descendant::button[contains(text(),'Edit')]</value>
      </entry>
      <entry>
         <key>BASIC</key>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>
